version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: kavak-agent-bot:latest
    container_name: kavak-agent-bot
    ports:
      - "8000:8000"
    env_file:
      - .env # aquí defines OPENAI_API_KEY, TWILIO_*, CATALOG_CSV_PATH, etc.
    restart: always
    # si tu catálogo está fuera de la imagen y quieres montarlo:
    # volumes:
    #   - ./data/catalog.csv:/app/data/catalog.csv:ro
